language: node_js
node_js:
  - lts/*
cache:
  npm: false
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  branches:
    only:
      - master
after_script:
  - cd dist
  - cd -
